[package]
name = "earcli"
version = "0.1.0"
edition = "2021"

[dependencies]
bluer = {version = "0.17.3", features = ["full"]}
clap = { version = "4.5.31", features = ["derive"] }
hex = "0.4.3"
tokio = {version = "1.43.0", features = ["full"]}
